language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test test --env=jsdom --coverage --collectCoverageFrom=src/lib/*.js --collectCoverageFrom=!src/lib/TestComponents/*.js
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master